### ISSUE TITLE
Redundant {% include JB/setup %} in sample post?

### ISSUE THREAD

**Issue by mchelen** [plusjade/jekyll-bootstrap#227]
The [sample post](https://github.com/plusjade/jekyll-bootstrap/blob/master/_posts/core-samples/2011-12-29-jekyll-introduction.md) has `{% include JB/setup %}` after the YAML.

Isn't `{% include JB/setup %}` already being run in the [post layout](https://github.com/plusjade/jekyll-bootstrap/blob/master/_layouts/post.html)?

It seems like the sample post should not need to include JB/setup as well.

**Comment by groundh0g** [comment]
I know this is an old issue, but ...

You're absolutely correct. I stripped the extraneous includes from my posts. As you said, it's not needed, and it's extra baggage if you make the move to another JB-like helper.

**Comment by groundh0g** [comment]
Assigning this to me. Low-hanging fruit.

Strip `{% include JB/setup %}` from:

```
jekyll-bootstrap/_posts/core-samples/2011-12-29-jekyll-introduction.md
```

**Comment by groundh0g** [comment]
After researching issue #113, it looks like this needs to stay as is. While it seems redundant, it's not.

Liquid variables are scoped to the page, so the page / post / default template includes the `JB/setup` snippet, but as soon as you hit an actual page / post / draft, the `page.whatever' variables are cleared and populated by the yaml header. So ...

The `{% include JB/setup %}` needs to stay in place so that `BASE_PATH` and `HOME_PATH` are properly set. See my notes in issue #113 on how the `ASSET_PATH` is unreliable at the page / post / draft level.
