### ISSUE TITLE
Collate a Sub-Set of Posts doesn't support tags in non-ascii characters?

### ISSUE THREAD

**Issue by 404pnf** [plusjade/jekyll-bootstrap#88]
Problem:  Collate a Sub-Set of Posts doesn't support tags in non-ascii characters, for example: passé, 中文标签

How to reproduce:

add either tag to some posts then add a page with

{% include JB/setup %}
{% assign posts_collate = site.tags.passé %}
{% include JB/posts_collate %}

No post returned.

If I passed in ascii tag name (test, jekyll) then posts with that tag returned.

According to the doc, it's supposed to return a list of tagged posts
http://jekyllbootstrap.com/api/bootstrap-api.html

Collate a Sub-Set of Posts

To collate a sub-set of posts, just pass in the sub-set. Bellow, only posts tagged “jekyll” will be collated:

{% assign posts_collate = site.tags.jekyll %}
{% include JB/posts_collate %}

**Comment by groundh0g** [comment]
Current behavior is that `site.tags.中文标签` results in same set as `site.tag` (the tag is ignored). To get at the subset, use the array notation - `site.tags["中文标签"]`. Worked in my local tests.

Closing this issue due to age, mention from commit b2828eb039ddc7c0108b6af06ca7f5d8c87a5459, and demonstrated work-around.
